import type { Metadata } from "next";
import { Geist, Manrope, Space_Grotesk, Urbanist, Vazirmatn } from "next/font/google";
import "./globals.css";

const ubranist = Urbanist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazir = Vazirmatn({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubranist.variable} ${spaceGrotesk.variable} ${vazir.variable} ${manrope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
